# Generated by Django 3.2.4 on 2021-06-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barsapi', '0002_remove_song_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='barsapi.playlist')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='barsapi.song')),
            ],
        ),
    ]
